"""Valid values for the fields of a workspace part that a test leaves unset, generated by `faker`.

Every value here is clean: the checks find nothing wrong with it. It honours the limits the Agent Skills
specification sets, and the rules of the default structure specification below, stated here rather than imported
from `lorecraft`, so a generated value checks the toolkit against the specification and not against itself:

- A skill's `description` is 1 to 1024 characters and not blank.
- A document's frontmatter `name`, where it writes one, is its file name without `.md`; `lib.workspace` writes it.
- A document under the default structure carries a frontmatter with a string `name` and `description`, one H1
  title before any section, a `Summary` section first and no empty section, at most 350 words in any section, and
  at most 1000 tokens in all.

A skill's `name`, a specification's name, and a document's corpus and name are not generated: the command prints
them, so a test always passes them.

The `faker` fixture is reseeded before each test, so a test generates the same values on every run.
"""

from faker import Faker


def skill_description(faker: Faker) -> str:
    """A one-line description of a skill: a sentence of a few words, far below the 1024-character limit.

    Args:
        faker: The test's seeded generator.
    """
    return faker.sentence()


def skill_body(faker: Faker) -> str:
    """The Markdown below a skill's frontmatter: a title heading and one paragraph, linking nothing.

    Args:
        faker: The test's seeded generator.
    """
    title = faker.word().capitalize()
    paragraph = faker.paragraph()
    return f'# {title}\n\n{paragraph}\n'


def spec_structure(faker: Faker) -> dict[str, object]:
    """The default structure specification: a rule from each check, so a document it accepts is clean for all of them.

    The frontmatter check reads the schema, the structure check the title, the empty sections and the outline, and
    the budget check the word caps and the token budget. Only the `description`, which no check reads, is generated.

    Args:
        faker: The test's seeded generator.
    """
    return {
        'description': faker.sentence(),
        'frontmatter': {
            'type': 'object',
            'required': ['name', 'description'],
            'properties': {
                'name': {'type': 'string'},
                'description': {'type': 'string'},
            },
        },
        'title': {'count': 1, 'first': True},
        'empty_sections': 'forbidden',
        'outline': [
            {'section': 'Summary', 'words': 350},
            {'any': True, 'words': 350},
        ],
        'tokens': 1000,
    }


def document_description(faker: Faker) -> str:
    """The `description` in a document's frontmatter: a sentence of a few words.

    Args:
        faker: The test's seeded generator.
    """
    return faker.sentence()


def document_body(faker: Faker) -> str:
    """The Markdown below a document's frontmatter: a title, then a `Summary` section holding one paragraph.

    A paragraph is a few sentences, far below the 350-word cap and the 1000-token budget.

    Args:
        faker: The test's seeded generator.
    """
    title = faker.word().capitalize()
    paragraph = faker.paragraph()
    return f'# {title}\n\n## Summary\n\n{paragraph}\n'
