"""Valid values for the fields of a workspace part that a test leaves unset, generated by `faker`.

Every value here is clean: the checks find nothing wrong with it. It honours the limits the Agent Skills
specification sets, stated here rather than imported from `lorecraft`, so a generated value checks the toolkit
against the specification and not against itself:

- A skill's `description` is 1 to 1024 characters and not blank.

A skill's `name` is not generated: the command prints it, so a test always passes it.

The `faker` fixture is reseeded before each test, so a test generates the same values on every run.
"""

from faker import Faker


def skill_description(faker: Faker) -> str:
    """A one-line description of a skill: a sentence of a few words, far below the 1024-character limit.

    Args:
        faker: The test's seeded generator.
    """
    return faker.sentence()


def skill_body(faker: Faker) -> str:
    """The Markdown below a skill's frontmatter: a title heading and one paragraph, linking nothing.

    Args:
        faker: The test's seeded generator.
    """
    title = faker.word().capitalize()
    paragraph = faker.paragraph()
    return f'# {title}\n\n{paragraph}\n'
