"""The specifications: their files, the schemas they state, and the repository that reads them.

That is the specification filenames and stems, the structure specification with the frontmatter schema it carries,
the repository that reads them, the skill frontmatter schema, and the problems both frontmatter schemas report.
"""

from .frontmatter_problem import (
    BlockProblem,
    FrontmatterProblem,
    InvalidValueProblem,
    MissingFieldProblem,
    NonStringKeyProblem,
    NotAStringMappingProblem,
    NotAStringProblem,
    UnknownFieldProblem,
    WrongTypeProblem,
)
from .name import SchemaName, parse_schema_name, schema_name_stem
from .repo import Repository, StructureSchemaReadError
from .skill import SKILL_FRONTMATTER_SCHEMA, SkillFrontmatterSchema
from .skill_frontmatter import (
    EmptySkillCompatibilityError,
    EmptySkillDescriptionError,
    EmptySkillNameError,
    InvalidSkillNameFormatError,
    OverlongSkillCompatibilityError,
    OverlongSkillDescriptionError,
    OverlongSkillNameError,
    SkillAllowedTools,
    SkillCompatibility,
    SkillDescription,
    SkillFrontmatter,
    SkillLicense,
    SkillName,
)
from .spec_file import (
    DottedSpecStemError,
    InvalidSpecStemError,
    NotASpecFileError,
    NotASpecStemError,
    SpecFile,
    SpecFileType,
    UnknownSpecFileTypeError,
    parse_spec_file,
    spec_filename,
)
from .structure import (
    AdjacentAnyRunsError,
    AnySections,
    EmptyStructureSpecError,
    ForbiddenOutlineSectionError,
    ForeignFrontmatterDialectError,
    FrontmatterSchema,
    FrontmatterSchemaIdError,
    InvalidFrontmatterSchemaError,
    InvalidTitleCountError,
    InvalidTokenBudgetError,
    InvalidWordCapError,
    OutlineEntry,
    RepeatedOutlineSectionError,
    SectionEntry,
    StructureSchema,
    StructureSpec,
    StructureSpecDecodeError,
    StructureSpecFilenameError,
    TitleRule,
    UntypedFrontmatterSchemaError,
)
from .structure_file import StructureFile

__all__ = [
    'SchemaName',
    'parse_schema_name',
    'schema_name_stem',
    'SpecFileType',
    'SpecFile',
    'parse_spec_file',
    'spec_filename',
    'DottedSpecStemError',
    'NotASpecFileError',
    'UnknownSpecFileTypeError',
    'NotASpecStemError',
    'InvalidSpecStemError',
    'StructureSchema',
    'StructureSpec',
    'FrontmatterSchema',
    'TitleRule',
    'StructureFile',
    'OutlineEntry',
    'SectionEntry',
    'AnySections',
    'StructureSpecDecodeError',
    'StructureSpecFilenameError',
    'EmptyStructureSpecError',
    'InvalidTitleCountError',
    'InvalidTokenBudgetError',
    'InvalidWordCapError',
    'RepeatedOutlineSectionError',
    'ForbiddenOutlineSectionError',
    'AdjacentAnyRunsError',
    'InvalidFrontmatterSchemaError',
    'FrontmatterSchemaIdError',
    'ForeignFrontmatterDialectError',
    'UntypedFrontmatterSchemaError',
    'StructureSchemaReadError',
    'Repository',
    'SkillFrontmatter',
    'SkillName',
    'EmptySkillNameError',
    'OverlongSkillNameError',
    'InvalidSkillNameFormatError',
    'SkillDescription',
    'EmptySkillDescriptionError',
    'OverlongSkillDescriptionError',
    'SkillLicense',
    'SkillCompatibility',
    'EmptySkillCompatibilityError',
    'OverlongSkillCompatibilityError',
    'SkillAllowedTools',
    'SkillFrontmatterSchema',
    'SKILL_FRONTMATTER_SCHEMA',
    'FrontmatterProblem',
    'MissingFieldProblem',
    'UnknownFieldProblem',
    'NonStringKeyProblem',
    'NotAStringProblem',
    'NotAStringMappingProblem',
    'WrongTypeProblem',
    'InvalidValueProblem',
    'BlockProblem',
]
