"""The specifications: their files, the schemas they state, and the repository that reads them.

That is the specification filenames and names, the structure specification with the frontmatter schema, the
counts and the section names it carries, the repository that reads them, the skill frontmatter schema, and the
problems both frontmatter schemas report, each placed on the line it is reported on.
"""

from .frontmatter_problem import (
    BlockProblem,
    FrontmatterProblem,
    InvalidValueProblem,
    MissingFieldProblem,
    UnknownFieldProblem,
    WrongTypeProblem,
)
from .name import CorpusSpecName, NamespaceSpecName, SpecName, parse_spec_name
from .repo import Repository, StructureSchemaReadError
from .schema_problems import (
    FIRST_LINE,
    AgentSkillsSchema,
    LocatedProblem,
    SchemaProblems,
    SchemaSource,
    StructureSpecSchema,
    field_line,
    locate_schema_problems,
    locate_skill_schema_problems,
)
from .section_name import EmptySectionNameError, MultilineSectionNameError, PaddedSectionNameError, SectionName
from .skill import SKILL_FRONTMATTER_SCHEMA, SkillFrontmatterSchema
from .skill_frontmatter import (
    EmptySkillCompatibilityError,
    EmptySkillDescriptionError,
    EmptySkillNameError,
    InvalidSkillNameFormatError,
    OverlongSkillCompatibilityError,
    OverlongSkillDescriptionError,
    OverlongSkillNameError,
    SkillAllowedTools,
    SkillCompatibility,
    SkillDescription,
    SkillFrontmatter,
    SkillLicense,
    SkillName,
)
from .spec_file import (
    DottedSpecStemError,
    InvalidSpecStemError,
    NotASpecFileError,
    NotASpecStemError,
    ProseSpecFile,
    SpecFile,
    SpecFileType,
    StructureSpecFile,
    UnknownSpecFileTypeError,
    parse_spec_file,
    spec_filename,
)
from .structure import (
    AdjacentAnyRunsError,
    AnySections,
    EmptyStructureSpecError,
    ForbiddenOutlineSectionError,
    ForeignFrontmatterDialectError,
    FrontmatterSchema,
    FrontmatterSchemaIdError,
    InvalidFrontmatterSchemaError,
    InvalidTitlePatternError,
    OutlineEntry,
    RepeatedForbiddenSectionError,
    RepeatedOutlineSectionError,
    SectionEntry,
    StructureSchema,
    StructureSpec,
    StructureSpecDecodeError,
    TitleChecks,
    TitlePattern,
    UntypedFrontmatterSchemaError,
)
from .structure_file import StructureFile

__all__: list[str] = [
    'CorpusSpecName',
    'NamespaceSpecName',
    'SpecName',
    'parse_spec_name',
    'SpecFileType',
    'ProseSpecFile',
    'StructureSpecFile',
    'SpecFile',
    'parse_spec_file',
    'spec_filename',
    'DottedSpecStemError',
    'NotASpecFileError',
    'UnknownSpecFileTypeError',
    'NotASpecStemError',
    'InvalidSpecStemError',
    'StructureSchema',
    'StructureSpec',
    'FrontmatterSchema',
    'StructureFile',
    'TitleChecks',
    'TitlePattern',
    'OutlineEntry',
    'SectionEntry',
    'SectionName',
    'EmptySectionNameError',
    'PaddedSectionNameError',
    'MultilineSectionNameError',
    'AnySections',
    'StructureSpecDecodeError',
    'EmptyStructureSpecError',
    'RepeatedOutlineSectionError',
    'RepeatedForbiddenSectionError',
    'ForbiddenOutlineSectionError',
    'AdjacentAnyRunsError',
    'InvalidTitlePatternError',
    'InvalidFrontmatterSchemaError',
    'FrontmatterSchemaIdError',
    'ForeignFrontmatterDialectError',
    'UntypedFrontmatterSchemaError',
    'StructureSchemaReadError',
    'Repository',
    'SkillFrontmatter',
    'SkillName',
    'EmptySkillNameError',
    'OverlongSkillNameError',
    'InvalidSkillNameFormatError',
    'SkillDescription',
    'EmptySkillDescriptionError',
    'OverlongSkillDescriptionError',
    'SkillLicense',
    'SkillCompatibility',
    'EmptySkillCompatibilityError',
    'OverlongSkillCompatibilityError',
    'SkillAllowedTools',
    'SkillFrontmatterSchema',
    'SKILL_FRONTMATTER_SCHEMA',
    'FrontmatterProblem',
    'MissingFieldProblem',
    'UnknownFieldProblem',
    'WrongTypeProblem',
    'InvalidValueProblem',
    'BlockProblem',
    'FIRST_LINE',
    'field_line',
    'SchemaSource',
    'StructureSpecSchema',
    'AgentSkillsSchema',
    'LocatedProblem',
    'SchemaProblems',
    'locate_schema_problems',
    'locate_skill_schema_problems',
]
